### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function is_writable() on bool 

### ISSUE THREAD

**Issue by s-acv2** [PopupMaker/Popup-Maker#1062]
## Describe the bug

Critical errors when visiting PUM Error Log and Subscribers.

## Site information
Popup Maker version: 1.18.2

WordPress version: 6.4.2

PHP version: X.X.X

## Expected behavior

Menu items are accessible.

## Current behavior

Fatal error occurring.

## Errors

```
[15-Feb-2024 13:32:57 UTC] PHP Fatal error: Uncaught Error: Call to a member function is_writable() on bool in /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Utils/Logging.php:85


Stack trace:
#0 /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Utils/Logging.php(65): PUM_Utils_Logging->__construct()
#1 /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/DB/Subscribers.php(126): PUM_Utils_Logging::instance()
#2 /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Abstract/Database.php(58): PUM_DB_Subscribers->create_table()
#3 /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Abstract/Database.php(118): PUM_Abstract_Database->__construct()
#4 /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Admin/Subscribers/Table.php(75): PUM_Abstract_Database::instance()
#5 /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Admin/Subscribers.php(30): PUM_Admin_Subscribers_Table->prepare_items()
#6 /home/w/wo/wordpress.org/htd in /home/w/wo/wordpress.org/htdocs/wp-content/plugins/popup-maker/classes/Utils/Logging.php on line 85
```

**Comment by danieliser** [comment]
Patched in `develop`, will go out with next release.
